# Generated by Django 2.0.13 on 2020-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_auto_20200602_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
